baseURL: "https://sicoz.github.io/"
languageCode: en-us
title: "Sicoz Blog"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: 'Hello there'
    Content: 'Wanna read some tech adventures?'
  socialIcons:
    - name: github
      url: "https://github.com/sicozz/"
    - name: instagram
      url: "https://www.instagram.com/sicoz21/"

  cover:
    linkFullImages: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30
